<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2014/10/09 19:18:23

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=homewww',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
