# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# default rules
#homepage:
#  url:   /
#  param: { module: default, action: index }


homepage:
  url: /
  param: { module: main, action:index }

homepage2:
  url: /index
  param: { module: main, action:index }
captcha:
  url: /captcha
  param: { module: main, action:captcha }
2colleft:
  url: /2-col-left
  param: { module: main, action:2colsleft }
phpbooks:
  url: /phpbooks
  param: { module: main, action:phpbooks }
tutorials:
  url: /tutorials
  param: { module: main, action:tutorials }
projects:
  url: /projects
  param: { module: main, action:projects }
tutorial1:
  url: /tutorials/xmlparsing
  param: { module: main, action:tutorial1 }
tutorial2parse:
  url: /tutorials/xmlparsing/parse
  param: { module: main, action:parse }
about:
  url: /about
  param: { module: main, action:about }

races:
  url: /races
  param: { module: main, action:races }

contact:
  url: /contact
  param: { module: main, action:contact }

scooby:
  url: /scooby
  param: { module: main, action:scooby }

# generic rules
# please, remove them by adding more specific rules
default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
